name = "promis"
main = "src/index.ts"
compatibility_date = "2026-01-14"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "receituario_db"
database_id = "af433617-be97-4768-8f47-b798c38fcbf8"
